/**
 * Suggested entry labels for each default profile category.
 * Keyed by category slug. Used to guide users on what to fill in next.
 */
export const CATEGORY_SUGGESTED_LABELS: Record<string, string[]> = {
  identity: [
    "Full name",
    "Preferred name",
    "Nickname",
    "Pronouns",
    "Date of birth",
    "Nationality",
    "Languages spoken",
    "Email",
    "Phone number",
    "Time zone",
  ],
  location: [
    "Current city",
    "Country",
    "Neighborhood",
    "Time zone",
    "Living situation",
    "Previous cities",
    "Dream city",
    "Home type",
    "Climate preference",
    "Remote/office",
  ],
  professional: [
    "Job title",
    "Company",
    "Industry",
    "Years of experience",
    "Key skills",
    "LinkedIn URL",
    "Work style",
    "Career stage",
    "Side projects",
    "Professional goals",
  ],
  education: [
    "Highest degree",
    "University",
    "Field of study",
    "Graduation year",
    "Certifications",
    "Learning style",
    "Currently learning",
    "Favorite subject",
    "Online courses",
    "Languages studied",
  ],
  relationships: [
    "Relationship status",
    "Partner's name",
    "Children",
    "Siblings",
    "Parents",
    "Best friend",
    "Pet(s)",
    "Family traditions",
    "Love language",
    "Important people",
  ],
  communication: [
    "Preferred tone",
    "Communication style",
    "Humor style",
    "Pet peeves",
    "Preferred channels",
    "Response time",
    "Meeting preference",
    "Feedback style",
    "Conflict style",
    "Small talk topics",
  ],
  personality: [
    "Myers-Briggs type",
    "Enneagram type",
    "Core values",
    "Strengths",
    "Weaknesses",
    "Life philosophy",
    "Role models",
    "Introvert/Extrovert",
    "Decision-making style",
    "Motivators",
  ],
  principles: [
    "Life motto",
    "Personal rule #1",
    "Personal rule #2",
    "Personal rule #3",
    "Framework I follow",
    "Book that shaped me",
    "Non-negotiable",
    "Daily habit",
    "Anti-goal",
    "Codex vitae entry",
  ],
  health: [
    "Blood type",
    "Allergies",
    "Dietary restrictions",
    "Exercise routine",
    "Sleep schedule",
    "Mental health practices",
    "Medications",
    "Fitness goals",
    "Preferred sport",
    "Wellness routine",
  ],
  hobbies: [
    "Favorite hobby",
    "Creative pursuit",
    "Sport/activity",
    "Weekend activity",
    "Collection",
    "Craft or DIY",
    "Outdoor activity",
    "Board games",
    "Volunteer work",
    "Bucket list hobby",
  ],
  food: [
    "Favorite foods",
    "Dietary style",
    "Cooking skill level",
    "Favorite restaurants",
    "Go-to recipe",
    "Coffee or tea",
    "Favorite snacks",
    "Food allergy",
    "Comfort food",
  ],
  entertainment: [
    "Favorite music genre",
    "Favorite music artists",
    "Favorite movies",
    "Favorite TV shows",
    "Favorite book",
    "Favorite podcast",
    "Favorite games",
    "Favorite characters",
    "Streaming services",
    "Currently watching",
    "Currently reading",
  ],
  travel: [
    "Countries visited",
    "Favorite destination",
    "Dream destination",
    "Travel style",
    "Passport(s)",
    "Frequent flyer program",
    "Last trip",
    "Next planned trip",
    "Travel bucket list",
    "Preferred accommodation",
  ],
  digital: [
    "Preferred OS",
    "Favorite app",
    "Tech stack",
    "Social media handles",
    "Website/blog",
    "GitHub username",
    "Favorite tool",
    "Keyboard layout",
    "Preferred browser",
    "Smart home setup",
  ],
  financial: [
    "Financial goal",
    "Investment style",
    "Budget method",
    "Savings goal",
    "Income source(s)",
    "Debt strategy",
    "Retirement plan",
    "Currency preference",
    "Crypto stance",
    "Charity/donations",
  ],
  goals: [
    "This year's goal",
    "5-year goal",
    "Life goal",
    "Career goal",
    "Health goal",
    "Learning goal",
    "Relationship goal",
    "Financial goal",
    "Anti-goal",
    "Legacy goal",
  ],
  preferences: [
    "Morning or night person",
    "Introvert or extrovert",
    "Planner or spontaneous",
    "Favorite season",
    "Favorite color",
    "Pet peeve",
    "Guilty pleasure",
    "Superpower wish",
    "Ideal weekend",
    "Noise preference",
  ],
};
