import { useState, useMemo, useEffect } from "react";
import { Copy, Check, Download, Plus, Trash2, Pencil, Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Separator } from "@/components/ui/separator";
import { supabase } from "@/integrations/supabase/client";
import type { ProfileCategory, ProfileEntry, AgentInstruction, ProfileView } from "@/hooks/useProfile";

interface Props {
  categories: ProfileCategory[];
  entries: ProfileEntry[];
  instructions: AgentInstruction[];
  views: ProfileView[];
  onSaveView: (data: Partial<ProfileView> & { id?: string }) => void;
  onDeleteView: (id: string) => void;
}

type ExportFormat = "structured" | "markdown" | "xml";

const DEFAULT_VIEWS = [
  { slug: "full", name: "Full profile", scopes: ["all", "professional", "personal", "health", "private"] },
  { slug: "professional", name: "Professional", scopes: ["all", "professional"] },
  { slug: "personal", name: "Personal", scopes: ["all", "personal"] },
  { slug: "health", name: "Health", scopes: ["all", "health"] },
];

const ALL_SCOPES = [
  { value: "all", label: "All" },
  { value: "professional", label: "Professional" },
  { value: "personal", label: "Personal" },
  { value: "health", label: "Health" },
  { value: "private", label: "Private" },
];

function getActiveScopes(viewSlug: string, customViews: ProfileView[]): string[] {
  const builtIn = DEFAULT_VIEWS.find((v) => v.slug === viewSlug);
  if (builtIn) return builtIn.scopes;
  const custom = customViews.find((v) => v.id === viewSlug);
  return custom?.included_scopes ?? ["all"];
}

function generateStructured(
  cats: ProfileCategory[],
  entries: ProfileEntry[],
  insts: AgentInstruction[],
  noteContents: Map<string, string>,
  includeNotes: boolean,
  includeInstructions: boolean,
  scopes: string[],
): string {
  const lines: string[] = ["ABOUT ME — Generated by Menerio", ""];
  const filtered = cats.filter((c) => scopes.includes(c.visibility_scope));
  for (const cat of filtered) {
    const catEntries = entries.filter((e) => e.category_id === cat.id);
    if (catEntries.length === 0) continue;
    lines.push(cat.name.toUpperCase());
    for (const entry of catEntries) {
      lines.push(`  ${entry.label}: ${entry.value}`);
      if (includeNotes && entry.linked_note_id && noteContents.has(entry.linked_note_id)) {
        lines.push(`  [Extended: ${noteContents.get(entry.linked_note_id)}]`);
      }
    }
    lines.push("");
  }
  if (includeInstructions) {
    const active = insts.filter((i) => i.is_active && scopes.includes(i.applies_to));
    if (active.length > 0) {
      lines.push("INSTRUCTIONS FOR AI");
      for (const inst of active) lines.push(`  - ${inst.instruction}`);
      lines.push("");
    }
  }
  return lines.join("\n").trim();
}

function generateMarkdown(
  cats: ProfileCategory[],
  entries: ProfileEntry[],
  insts: AgentInstruction[],
  noteContents: Map<string, string>,
  includeNotes: boolean,
  includeInstructions: boolean,
  scopes: string[],
): string {
  const lines: string[] = ["## About Me", ""];
  const filtered = cats.filter((c) => scopes.includes(c.visibility_scope));
  for (const cat of filtered) {
    const catEntries = entries.filter((e) => e.category_id === cat.id);
    if (catEntries.length === 0) continue;
    lines.push(`### ${cat.name}`);
    for (const entry of catEntries) {
      lines.push(`- **${entry.label}**: ${entry.value}`);
      if (includeNotes && entry.linked_note_id && noteContents.has(entry.linked_note_id)) {
        lines.push(`  > ${noteContents.get(entry.linked_note_id)}`);
      }
    }
    lines.push("");
  }
  if (includeInstructions) {
    const active = insts.filter((i) => i.is_active && scopes.includes(i.applies_to));
    if (active.length > 0) {
      lines.push("### Instructions for AI");
      for (const inst of active) lines.push(`- ${inst.instruction}`);
      lines.push("");
    }
  }
  return lines.join("\n").trim();
}

function generateXml(
  cats: ProfileCategory[],
  entries: ProfileEntry[],
  insts: AgentInstruction[],
  noteContents: Map<string, string>,
  includeNotes: boolean,
  includeInstructions: boolean,
  scopes: string[],
): string {
  const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  const lines: string[] = [`<user_profile source="menerio" generated="${new Date().toISOString().split("T")[0]}">`];
  const filtered = cats.filter((c) => scopes.includes(c.visibility_scope));
  for (const cat of filtered) {
    const catEntries = entries.filter((e) => e.category_id === cat.id);
    if (catEntries.length === 0) continue;
    lines.push(`  <category name="${esc(cat.name)}">`);
    for (const entry of catEntries) {
      if (includeNotes && entry.linked_note_id && noteContents.has(entry.linked_note_id)) {
        lines.push(`    <entry label="${esc(entry.label)}" linked_note="true">`);
        lines.push(`      ${esc(entry.value)}`);
        lines.push(`      ${esc(noteContents.get(entry.linked_note_id)!)}`);
        lines.push(`    </entry>`);
      } else {
        lines.push(`    <entry label="${esc(entry.label)}">${esc(entry.value)}</entry>`);
      }
    }
    lines.push(`  </category>`);
  }
  if (includeInstructions) {
    const active = insts.filter((i) => i.is_active && scopes.includes(i.applies_to));
    if (active.length > 0) {
      lines.push(`  <agent_instructions>`);
      for (const inst of active) lines.push(`    <instruction>${esc(inst.instruction)}</instruction>`);
      lines.push(`  </agent_instructions>`);
    }
  }
  lines.push(`</user_profile>`);
  return lines.join("\n");
}

export function ExportTab({ categories, entries, instructions, views, onSaveView, onDeleteView }: Props) {
  const [viewSlug, setViewSlug] = useState("full");
  const [format, setFormat] = useState<ExportFormat>("structured");
  const [includeNotes, setIncludeNotes] = useState(false);
  const [includeInstructions, setIncludeInstructions] = useState(true);
  const [copied, setCopied] = useState(false);
  const [noteContents, setNoteContents] = useState<Map<string, string>>(new Map());

  // Manage views
  const [addingView, setAddingView] = useState(false);
  const [editingViewId, setEditingViewId] = useState<string | null>(null);
  const [viewName, setViewName] = useState("");
  const [viewScopes, setViewScopes] = useState<string[]>(["all"]);

  // Fetch linked note contents when toggle is on
  useEffect(() => {
    if (!includeNotes) return;
    const noteIds = entries.filter((e) => e.linked_note_id).map((e) => e.linked_note_id!);
    if (noteIds.length === 0) return;
    const unique = [...new Set(noteIds)];
    supabase
      .from("notes")
      .select("id, content")
      .in("id", unique)
      .then(({ data }) => {
        const map = new Map<string, string>();
        data?.forEach((n) => map.set(n.id, n.content));
        setNoteContents(map);
      });
  }, [includeNotes, entries]);

  const scopes = useMemo(() => getActiveScopes(viewSlug, views), [viewSlug, views]);

  const exportText = useMemo(() => {
    const gen = format === "xml" ? generateXml : format === "markdown" ? generateMarkdown : generateStructured;
    return gen(categories, entries, instructions, noteContents, includeNotes, includeInstructions, scopes);
  }, [categories, entries, instructions, noteContents, includeNotes, includeInstructions, scopes, format]);

  const handleCopy = () => {
    navigator.clipboard.writeText(exportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const ext = format === "xml" ? "xml" : format === "markdown" ? "md" : "txt";
    const viewName = DEFAULT_VIEWS.find((v) => v.slug === viewSlug)?.name ?? views.find((v) => v.id === viewSlug)?.name ?? "profile";
    const slug = viewName.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    const blob = new Blob([exportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `menerio-profile-${slug}.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleSaveView = () => {
    if (!viewName.trim()) return;
    onSaveView({
      id: editingViewId ?? undefined,
      name: viewName.trim(),
      included_scopes: viewScopes,
    });
    setAddingView(false);
    setEditingViewId(null);
    setViewName("");
    setViewScopes(["all"]);
  };

  const toggleScope = (scope: string) => {
    setViewScopes((prev) =>
      prev.includes(scope) ? prev.filter((s) => s !== scope) : [...prev, scope]
    );
  };

  return (
    <div className="space-y-6">
      {/* Export configuration */}
      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-start gap-3">
            <div className="h-9 w-9 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
              <Share2 className="h-4.5 w-4.5 text-primary" />
            </div>
            <div>
              <h3 className="text-lg font-semibold">Export & Share</h3>
              <p className="text-sm text-muted-foreground mt-1">
                Generate a formatted "About Me" block to paste into any AI tool's system prompt or custom instructions.
              </p>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-5">
          {/* Controls */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <Label className="text-xs text-muted-foreground">Profile view</Label>
              <Select value={viewSlug} onValueChange={setViewSlug}>
                <SelectTrigger className="text-sm"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {DEFAULT_VIEWS.map((v) => (
                    <SelectItem key={v.slug} value={v.slug}>{v.name}</SelectItem>
                  ))}
                  {views.map((v) => (
                    <SelectItem key={v.id} value={v.id}>{v.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label className="text-xs text-muted-foreground">Format</Label>
              <Select value={format} onValueChange={(v) => setFormat(v as ExportFormat)}>
                <SelectTrigger className="text-sm"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="structured">Structured text</SelectItem>
                  <SelectItem value="markdown">Markdown</SelectItem>
                  <SelectItem value="xml">XML tags</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-4">
            <div className="flex items-center gap-2">
              <Switch id="include-notes" checked={includeNotes} onCheckedChange={setIncludeNotes} />
              <Label htmlFor="include-notes" className="text-sm cursor-pointer">Include linked note content</Label>
            </div>
            <div className="flex items-center gap-2">
              <Switch id="include-instructions" checked={includeInstructions} onCheckedChange={setIncludeInstructions} />
              <Label htmlFor="include-instructions" className="text-sm cursor-pointer">Include agent instructions</Label>
            </div>
          </div>

          <Separator />

          {/* Preview */}
          <div className="relative">
            <pre className="text-sm font-mono whitespace-pre-wrap rounded-lg border border-border bg-muted/30 p-4 max-h-[400px] overflow-auto">
              {exportText || <span className="text-muted-foreground italic">No profile data to export yet. Add entries in the Profile tab first.</span>}
            </pre>
          </div>

          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handleCopy} disabled={!exportText}>
              {copied ? <Check className="h-3.5 w-3.5 mr-1" /> : <Copy className="h-3.5 w-3.5 mr-1" />}
              {copied ? "Copied!" : "Copy to clipboard"}
            </Button>
            <Button variant="outline" size="sm" onClick={handleDownload} disabled={!exportText}>
              <Download className="h-3.5 w-3.5 mr-1" /> Download as .{format === "xml" ? "xml" : format === "markdown" ? "md" : "txt"}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Profile Views Manager */}
      <Card>
        <CardHeader className="pb-3">
          <h3 className="text-lg font-semibold">Profile Views</h3>
          <p className="text-sm text-muted-foreground">
            Named presets that control which categories are included in an export based on their visibility scopes.
          </p>
        </CardHeader>
        <CardContent className="space-y-3">
          {/* Built-in views */}
          {DEFAULT_VIEWS.map((v) => (
            <div key={v.slug} className="flex items-center gap-3 rounded-lg border border-border p-3">
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium">{v.name}</p>
                <p className="text-xs text-muted-foreground">
                  Scopes: {v.scopes.join(", ")}
                </p>
              </div>
              <span className="text-xs text-muted-foreground">Built-in</span>
            </div>
          ))}

          {/* Custom views */}
          {views.map((v) =>
            editingViewId === v.id ? (
              <ViewForm
                key={v.id}
                name={viewName}
                scopes={viewScopes}
                onNameChange={setViewName}
                onToggleScope={toggleScope}
                onSave={handleSaveView}
                onCancel={() => { setEditingViewId(null); setViewName(""); setViewScopes(["all"]); }}
              />
            ) : (
              <div key={v.id} className="flex items-center gap-3 rounded-lg border border-border p-3 group hover:bg-accent/20 transition-colors">
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium">{v.name}</p>
                  <p className="text-xs text-muted-foreground">
                    Scopes: {v.included_scopes.join(", ")}
                  </p>
                </div>
                <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                  <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => {
                    setEditingViewId(v.id);
                    setViewName(v.name);
                    setViewScopes([...v.included_scopes]);
                  }}>
                    <Pencil className="h-3.5 w-3.5" />
                  </Button>
                  <Button variant="ghost" size="icon" className="h-7 w-7 text-destructive" onClick={() => onDeleteView(v.id)}>
                    <Trash2 className="h-3.5 w-3.5" />
                  </Button>
                </div>
              </div>
            )
          )}

          {addingView ? (
            <ViewForm
              name={viewName}
              scopes={viewScopes}
              onNameChange={setViewName}
              onToggleScope={toggleScope}
              onSave={handleSaveView}
              onCancel={() => { setAddingView(false); setViewName(""); setViewScopes(["all"]); }}
            />
          ) : (
            <Button variant="outline" size="sm" onClick={() => { setAddingView(true); setEditingViewId(null); }}>
              <Plus className="h-3.5 w-3.5 mr-1" /> Add custom view
            </Button>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

function ViewForm({
  name,
  scopes,
  onNameChange,
  onToggleScope,
  onSave,
  onCancel,
}: {
  name: string;
  scopes: string[];
  onNameChange: (v: string) => void;
  onToggleScope: (scope: string) => void;
  onSave: () => void;
  onCancel: () => void;
}) {
  return (
    <div className="rounded-lg border border-border p-4 bg-muted/30 space-y-3">
      <Input
        placeholder="View name, e.g. Coding Assistant"
        value={name}
        onChange={(e) => onNameChange(e.target.value)}
        className="text-sm"
      />
      <div className="flex flex-wrap gap-3">
        {ALL_SCOPES.map((s) => (
          <label key={s.value} className="flex items-center gap-1.5 text-sm cursor-pointer">
            <Checkbox
              checked={scopes.includes(s.value)}
              onCheckedChange={() => onToggleScope(s.value)}
            />
            {s.label}
          </label>
        ))}
      </div>
      <div className="flex gap-2 justify-end">
        <Button variant="ghost" size="sm" onClick={onCancel}>Cancel</Button>
        <Button size="sm" onClick={onSave} disabled={!name.trim() || scopes.length === 0}>Save</Button>
      </div>
    </div>
  );
}
