import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY") || Deno.env.get("SUPABASE_PUBLISHABLE_KEY")!;
const OPENROUTER_API_KEY = Deno.env.get("OPENROUTER_API_KEY")!;
const OPENROUTER_MODEL = "openai/gpt-4o-mini";

const DRIFT_AND_CONTRADICTION_AUDITOR_PROMPT = `You are the auditor for a personal LLM-maintained knowledge base in the style of Andrej Karpathy's LLM Wiki pattern. Your job is to find specific failure modes: contradictions, drift (confident prose not supported by sources), gaps (missing important connections), and stale syntheses (pages that newer pages have superseded).

The pages to audit follow this system prompt as the user-role message. Each shows slug, title, page_type, and full markdown content.

# What to look for

1. **Contradictions.** Two pages making opposite or incompatible claims about the same thing, OR a single page that contradicts itself between sections. Be CONSERVATIVE — flag only clear contradictions, not differences in framing or emphasis. If a page already has a "## Contradictions" section, read it first and only flag NEW contradictions not already documented.

2. **Drift.** Confident prose that is not visibly supported by surrounding content or other pages. Statements that read as facts but appear to have been generated by an LLM during synthesis without grounding. Flag the specific sentence or section.

3. **Gaps.** Important connections that should exist but don't. A project page that doesn't link to its people. A concept page that doesn't link to its instances. Flag the missing link, not the entire page.

4. **Stale syntheses.** Pages whose claims appear out of date relative to other newer pages. Page A says "X has not happened yet" while a newer page B describes X as completed. Content-based — do not flag based on dates alone.

# Rules

- Be conservative across all four categories. False positives waste the user's review time. When in doubt, don't flag.

- Each finding must be specific and actionable. "Page X has issues" is not useful; "Page X states 'Sarah leads the ML team' but page Y states 'Sarah left the company'" is.

- If you find no issues in a category, return an empty array.

- If fewer than two pages are provided, you cannot find contradictions or stale syntheses — return empty arrays for those.

- Severity scale:

  - high: factual contradiction, broken trust, or critical missing link

  - medium: likely problem the user should review

  - low: soft signal worth noting but not urgent

# Output

Return ONLY a JSON object, no surrounding text, no code fences:

{

  "contradictions": [

    {

      "pages": ["slug-a", "slug-b"],

      "description": "Concise description of the contradiction. Quote the conflicting claims.",

      "severity": "high|medium|low",

      "suggested_fix": "Brief suggestion."

    }

  ],

  "drift": [

    {

      "page": "slug",

      "section": "Header or section name where the claim appears",

      "description": "Description of the unsupported claim. Quote it.",

      "severity": "high|medium|low",

      "suggested_fix": "Brief suggestion."

    }

  ],

  "gaps": [

    {

      "page": "slug",

      "missing_link": "target-slug-or-name-of-thing-not-linked",

      "description": "What's missing and why it should be linked.",

      "severity": "high|medium|low",

      "suggested_fix": "Brief suggestion."

    }

  ],

  "stale_syntheses": [

    {

      "page": "slug",

      "description": "What appears out of date and which newer page contradicts or supersedes it.",

      "severity": "high|medium|low",

      "suggested_fix": "Brief suggestion."

    }

  ]

}`;

type WikiPage = {
  id: string;
  slug: string;
  title: string;
  page_type: string;
  content: string;
  updated_at: string;
};

type AuditorResult = {
  contradictions: Array<{ pages: string[]; description: string; severity: string; suggested_fix: string }>;
  drift: Array<{ page: string; section: string; description: string; severity: string; suggested_fix: string }>;
  gaps: Array<{ page: string; missing_link: string; description: string; severity: string; suggested_fix: string }>;
  stale_syntheses: Array<{ page: string; description: string; severity: string; suggested_fix: string }>;
};

function jsonResponse(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function extractBearer(req: Request) {
  const header = req.headers.get("Authorization") || "";
  return header.startsWith("Bearer ") ? header.slice(7) : null;
}

function daysSince(date: string) {
  return Math.floor((Date.now() - new Date(date).getTime()) / 86_400_000);
}

function normalizeAuditorResult(value: unknown): AuditorResult {
  const obj = value && typeof value === "object" ? value as Record<string, unknown> : {};
  return {
    contradictions: Array.isArray(obj.contradictions) ? obj.contradictions as AuditorResult["contradictions"] : [],
    drift: Array.isArray(obj.drift) ? obj.drift as AuditorResult["drift"] : [],
    gaps: Array.isArray(obj.gaps) ? obj.gaps as AuditorResult["gaps"] : [],
    stale_syntheses: Array.isArray(obj.stale_syntheses) ? obj.stale_syntheses as AuditorResult["stale_syntheses"] : [],
  };
}

function extractJson(text: string) {
  const trimmed = text.trim();
  try {
    return JSON.parse(trimmed);
  } catch {
    const start = trimmed.indexOf("{");
    const end = trimmed.lastIndexOf("}");
    if (start === -1 || end === -1 || end <= start) throw new Error("No JSON object found");
    return JSON.parse(trimmed.slice(start, end + 1));
  }
}

async function callAuditor(userContent: string): Promise<{ result: AuditorResult; raw: string }> {
  if (!OPENROUTER_API_KEY) throw new Error("OPENROUTER_API_KEY is not configured");

  const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${OPENROUTER_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: OPENROUTER_MODEL,
      messages: [
        { role: "system", content: DRIFT_AND_CONTRADICTION_AUDITOR_PROMPT },
        { role: "user", content: userContent },
      ],
      temperature: 0.1,
      response_format: { type: "json_object" },
    }),
  });

  if (!response.ok) {
    const text = await response.text().catch(() => "");
    throw new Error(`LLM audit failed: ${response.status} ${text}`);
  }

  const data = await response.json();
  const raw = data.choices?.[0]?.message?.content || "";
  return { result: normalizeAuditorResult(extractJson(raw)), raw };
}

function formatPagesForAudit(pages: WikiPage[]) {
  return pages.map((page) => [
    `slug: ${page.slug}`,
    `title: ${page.title}`,
    `page_type: ${page.page_type}`,
    "content:",
    page.content || "",
  ].join("\n")).join("\n\n---\n\n");
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return jsonResponse({ error: "Method not allowed" }, 405);

  const startedAt = Date.now();
  let db: any = null;
  let userId: string | null = null;

  try {
    const token = extractBearer(req);
    if (!token) return jsonResponse({ error: "Unauthenticated" }, 401);

    const authClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    const { data: userData, error: userError } = await authClient.auth.getUser(token);
    if (userError || !userData.user) return jsonResponse({ error: "Unauthenticated" }, 401);
    userId = userData.user.id;

    db = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      global: { headers: { Authorization: `Bearer ${token}` } },
    });

    const { data: pages, error: pagesError } = await db
      .from("wiki_pages")
      .select("id, slug, title, page_type, content, updated_at")
      .order("updated_at", { ascending: false });
    if (pagesError) throw pagesError;

    const allPages = (pages || []) as WikiPage[];
    const pageById = new Map(allPages.map((page) => [page.id, page]));

    if (allPages.length === 0) {
      const emptyResult = {
        unresolved_wikilinks: [],
        orphan_pages: [],
        age_stale_pages: [],
        contradictions: [],
        drift: [],
        gaps: [],
        stale_syntheses: [],
        llm_error: null,
      };
      await db.from("wiki_log").insert({ user_id: userId, operation: "lint", details: { counts: {}, duration_ms: Date.now() - startedAt } });
      return jsonResponse({ ok: true, findings: emptyResult });
    }

    const { data: links, error: linksError } = await db
      .from("wiki_links")
      .select("source_page_id, target_slug, target_page_id");
    if (linksError) throw linksError;

    const unresolvedWikilinks = (links || [])
      .filter((link: any) => link.target_page_id === null)
      .map((link: any) => {
        const source = pageById.get(link.source_page_id);
        return {
          source_page_slug: source?.slug || "unknown",
          source_page_title: source?.title || "Unknown page",
          target_slug: link.target_slug,
        };
      });

    const linkedTargetIds = new Set((links || []).map((link: any) => link.target_page_id).filter(Boolean));
    const orphanPages = allPages
      .filter((page) => !linkedTargetIds.has(page.id))
      .map((page) => ({ slug: page.slug, title: page.title, page_type: page.page_type, updated_at: page.updated_at }));

    const cutoff60 = new Date(Date.now() - 60 * 86_400_000).toISOString();
    const cutoff30 = new Date(Date.now() - 30 * 86_400_000).toISOString();
    const { count: recentNotesCount, error: recentNotesError } = await db
      .from("notes")
      .select("id", { count: "exact", head: true })
      .gte("created_at", cutoff30);
    if (recentNotesError) throw recentNotesError;

    let ageStalePages: Array<{ slug: string; title: string; updated_at: string; days_since_update: number }> = [];
    if ((recentNotesCount || 0) > 0) {
      const staleCandidates = allPages.filter((page) => page.updated_at < cutoff60);
      const candidateIds = staleCandidates.map((page) => page.id);
      if (candidateIds.length > 0) {
        const { data: sources, error: sourcesError } = await db
          .from("wiki_page_sources")
          .select("wiki_page_id, note_id")
          .in("wiki_page_id", candidateIds);
        if (sourcesError) throw sourcesError;

        const noteIds = [...new Set((sources || []).map((source: any) => source.note_id).filter(Boolean))];
        const { data: sourceNotes, error: sourceNotesError } = noteIds.length > 0
          ? await db.from("notes").select("id, created_at").in("id", noteIds)
          : { data: [], error: null };
        if (sourceNotesError) throw sourceNotesError;

        const noteCreatedAt = new Map((sourceNotes || []).map((note: any) => [note.id, note.created_at]));
        ageStalePages = staleCandidates.filter((page) => {
          const pageSources = (sources || []).filter((source: any) => source.wiki_page_id === page.id);
          return pageSources.length > 0 && pageSources.every((source: any) => {
            const createdAt = noteCreatedAt.get(source.note_id);
            return createdAt && createdAt < cutoff60;
          });
        }).map((page) => ({
          slug: page.slug,
          title: page.title,
          updated_at: page.updated_at,
          days_since_update: daysSince(page.updated_at),
        }));
      }
    }

    let auditor = normalizeAuditorResult({});
    let llmError: string | null = null;
    const pagesForAudit = allPages.slice(0, 20);
    try {
      const audited = await callAuditor(formatPagesForAudit(pagesForAudit));
      auditor = audited.result;
    } catch (error) {
      llmError = error instanceof Error ? error.message : String(error);
      console.error("wiki-lint auditor failed", error);
    }

    const findings = {
      unresolved_wikilinks: unresolvedWikilinks,
      orphan_pages: orphanPages,
      age_stale_pages: ageStalePages,
      contradictions: auditor.contradictions,
      drift: auditor.drift,
      gaps: auditor.gaps,
      stale_syntheses: auditor.stale_syntheses,
      llm_error: llmError,
    };

    const counts = {
      unresolved_wikilinks: unresolvedWikilinks.length,
      orphan_pages: orphanPages.length,
      age_stale_pages: ageStalePages.length,
      contradictions: auditor.contradictions.length,
      drift: auditor.drift.length,
      gaps: auditor.gaps.length,
      stale_syntheses: auditor.stale_syntheses.length,
    };

    await db.from("wiki_log").insert({
      user_id: userId,
      operation: "lint",
      details: { counts, llm_error: llmError, audited_page_count: pagesForAudit.length, duration_ms: Date.now() - startedAt },
    });

    return jsonResponse({ ok: true, findings, counts, duration_ms: Date.now() - startedAt });
  } catch (error) {
    console.error("wiki-lint failed", error);
    if (db && userId) {
      await db.from("wiki_log").insert({
        user_id: userId,
        operation: "lint_failed",
        details: { error: error instanceof Error ? error.message : String(error), duration_ms: Date.now() - startedAt },
      }).catch((logError: unknown) => console.error("failed to log wiki lint failure", logError));
    }
    return jsonResponse({ error: "Wiki lint failed" }, 500);
  }
});
